name: Test Suite
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Install Project
        run: uv sync --locked --all-groups --all-extras

      - name: Run Tests
        run: uv run pytest tests/ --cov=wandern --cov-report=term-missing --cov-report=xml

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .coverage

      - name: Codecov coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
